const fs = require('fs');
const ragEngine = require('./src/engine/ragEngine');
const data = JSON.parse(fs.readFileSync('data/rag_index.json', 'utf8'));
const chunk = data.find(item => item.id === 'added-from-backup-1');
if (!chunk) throw new Error('chunk not found');
const clone = JSON.parse(JSON.stringify(chunk));
clone.program = 'SI';
clone.wave = '1A';
clone.academicYear = '2026';
clone.partner = null;
const queryEntitiesA = {intent:'COST', academicIntent:'BIAYA', program:'SI', wave:'1A', academicYear:'2025'};
const queryEntitiesB = {intent:'COST', academicIntent:'BIAYA', program:'SI', wave:'1A', academicYear:'2026'};
console.log('=== BEFORE INJECTION ===');
console.log(JSON.stringify({ id: chunk.id, filename: chunk.filename, academicYear: chunk.academicYear, program: chunk.program, wave: chunk.wave, partner: chunk.partner }, null, 2));
console.log('getChunkEntities BEFORE', JSON.stringify(ragEngine.getChunkEntities(chunk), null, 2));
console.log('--- result BEFORE ---');
console.log(JSON.stringify(ragEngine.tryStructuredExactCostAnswer('berapa biaya SI gelombang 1A 2025?', queryEntitiesA, [chunk], 3, null), null, 2));
console.log('\n=== AFTER INJECTION ===');
console.log(JSON.stringify({ id: clone.id, filename: clone.filename, academicYear: clone.academicYear, program: clone.program, wave: clone.wave, partner: clone.partner }, null, 2));
console.log('getChunkEntities AFTER', JSON.stringify(ragEngine.getChunkEntities(clone), null, 2));
console.log('--- result AFTER (query year 2025) ---');
console.log(JSON.stringify(ragEngine.tryStructuredExactCostAnswer('berapa biaya SI gelombang 1A 2025?', queryEntitiesA, [clone], 3, null), null, 2));
console.log('--- result AFTER (query year 2026) ---');
console.log(JSON.stringify(ragEngine.tryStructuredExactCostAnswer('berapa biaya SI gelombang 1A 2026?', queryEntitiesB, [clone], 3, null), null, 2));
