const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { chunkText } = require('./chunker');
const { classifyDocumentCategoryDetailed } = require('./docCategoryClassifier');

const RUNTIME_DIR = path.resolve(__dirname, '..', '..', 'data', 'runtime');
const MANIFEST_PATH = path.join(RUNTIME_DIR, 'knowledge_preparation_manifest.jsonl');
const SOURCE_REGISTRY_PATH = path.join(RUNTIME_DIR, 'knowledge_source_registry.json');

function compact(value) {
  return String(value || '').replace(/\s+/g, ' ').trim();
}

function normalize(value) {
  return compact(value).toLowerCase().replace(/[^\p{L}\p{N}\s]/gu, ' ').replace(/\s+/g, ' ').trim();
}

function sha256(value) {
  return crypto.createHash('sha256').update(String(value || '')).digest('hex');
}

function readJsonFileSafe(filePath, fallback) {
  try {
    if (!fs.existsSync(filePath)) return fallback;
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (_) {
    return fallback;
  }
}

function unique(items, max = 30) {
  const seen = new Set();
  const out = [];
  for (const item of Array.isArray(items) ? items : []) {
    const value = compact(item);
    const key = normalize(value);
    if (!value || seen.has(key)) continue;
    seen.add(key);
    out.push(value);
    if (out.length >= max) break;
  }
  return out;
}

function defaultSourceRegistry() {
  return {
    version: 1,
    authorities: [
      { pattern: "akreditasi|ban\\s*-?pt|lam\\s*-?infokom|sk\\s+lam|surat\\s+keputusan", level: "high", reason: "official_accreditation_source" },
      { pattern: "pmb|pendaftaran|rincian\\s+biaya|biaya|gelombang|siap\\.stikom", level: "high", reason: "official_admission_source" },
      { pattern: "kurikulum|rps|sks|program\\s+studi|prodi|fakultas", level: "medium", reason: "academic_program_source" },
      { pattern: "hima|ukm|ormawa|dpm|bem|inkubator|inbis|career\\s+center|llc", level: "medium", reason: "student_service_source" },
      { pattern: "draft|template|contoh|sample|dummy|sementara", level: "low", reason: "draft_or_unapproved_source" }
    ]
  };
}

function ensureSourceRegistry() {
  fs.mkdirSync(RUNTIME_DIR, { recursive: true });
  if (!fs.existsSync(SOURCE_REGISTRY_PATH)) {
    fs.writeFileSync(SOURCE_REGISTRY_PATH, JSON.stringify(defaultSourceRegistry(), null, 2), 'utf8');
  }
  return readJsonFileSafe(SOURCE_REGISTRY_PATH, defaultSourceRegistry());
}

function stripHeaderFooterNoise(content) {
  const lines = String(content || '').split(/\r?\n/).map((line) => line.replace(/\s+/g, ' ').trim());
  const counts = new Map();
  for (const line of lines) {
    const key = normalize(line);
    if (!key || key.length > 120) continue;
    counts.set(key, (counts.get(key) || 0) + 1);
  }
  const repeatThreshold = Math.max(3, Math.ceil(lines.length * 0.08));
  const cleaned = [];
  for (const line of lines) {
    const key = normalize(line);
    const repeated = key && counts.get(key) >= repeatThreshold;
    const pageMarker = /^(?:page|halaman|hlm\.?)\s*\d+(?:\s*(?:of|dari)\s*\d+)?$/i.test(line) || /^[-–—]?\s*\d+\s*[-–—]?$/.test(line);
    const fileNoise = /^(?:confidential|generated by|sent via|printed on|downloaded on|scan(?:ned)? by|cam scanner|camscanner|powered by|dokumen ini dicetak|dicetak pada)\b/i.test(line);
    const watermark = /^(?:draft|confidential|internal use only|page intentionally left blank)$/i.test(line);
    const urlOnly = /^(?:https?:\/\/|www\.)\S+$/i.test(line);
    if (repeated || pageMarker || fileNoise || watermark || urlOnly) continue;
    cleaned.push(line);
  }
  return cleaned.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

function splitTableRow(line) {
  const raw = String(line || '').trim();
  if (!raw) return [];
  if (raw.includes('|')) return raw.split('|').map(compact).filter(Boolean);
  if (raw.includes('\t')) return raw.split(/\t+/).map(compact).filter(Boolean);
  if (raw.includes(';') && /(?:rp|biaya|prodi|gelombang|tanggal|sks|akreditasi|program|nama)/i.test(raw)) return raw.split(';').map(compact).filter(Boolean);
  if (/\s{2,}/.test(raw)) return raw.split(/\s{2,}/).map(compact).filter(Boolean);
  return [];
}

function inferTableDomain(headerText, rowText) {
  const hay = normalize([headerText, rowText].join(' '));
  if (/\b(?:biaya|dpp|ukt|spp|pendaftaran|gelombang|rp|angsuran)\b/.test(hay)) return 'fee_table';
  if (/\b(?:jadwal|tanggal|semester|agenda|periode|mulai|akhir)\b/.test(hay)) return 'schedule_table';
  if (/\b(?:akreditasi|sk|ban pt|lam infokom|peringkat)\b/.test(hay)) return 'accreditation_table';
  if (/\b(?:sks|mata kuliah|kurikulum|semester|kode mk)\b/.test(hay)) return 'curriculum_table';
  if (/\b(?:prodi|program studi|jenjang|fakultas)\b/.test(hay)) return 'program_table';
  return 'generic_table';
}

function extractStructuredTables(text) {
  const lines = String(text || '').split(/\r?\n/);
  const tables = [];
  let current = [];

  const flush = () => {
    if (current.length < 2) { current = []; return; }
    const parsed = current.map((item) => ({ line: item.line, cells: splitTableRow(item.text) })).filter((row) => row.cells.length >= 2);
    current = [];
    if (parsed.length < 2) return;
    const maxCols = Math.max(...parsed.map((row) => row.cells.length));
    if (maxCols < 2) return;
    const header = parsed[0].cells;
    const rows = parsed.slice(1).map((row) => {
      const out = {};
      for (let i = 0; i < Math.min(maxCols, 12); i += 1) {
        const key = header[i] || ('col' + (i + 1));
        const value = row.cells[i] || '';
        if (value) out[key] = value;
      }
      return out;
    }).filter((row) => Object.keys(row).length);
    if (!rows.length) return;
    const headerText = header.join(' ');
    const rowText = rows.slice(0, 6).map((row) => Object.values(row).join(' ')).join(' ');
    tables.push({
      tableId: 'table_' + (tables.length + 1),
      startLine: parsed[0].line,
      endLine: parsed[parsed.length - 1].line,
      domain: inferTableDomain(headerText, rowText),
      columnCount: maxCols,
      rowCount: rows.length,
      headers: header.slice(0, 12),
      rows: rows.slice(0, 25)
    });
  };

  lines.forEach((line, idx) => {
    const cells = splitTableRow(line);
    if (cells.length >= 2) current.push({ line: idx + 1, text: line });
    else flush();
  });
  flush();

  return tables.slice(0, 20);
}

function detectDocumentStructure(text) {
  const rawLines = String(text || '').split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
  const headings = [];
  const tables = [];
  const lists = [];
  let questionLike = 0;
  rawLines.forEach((line, index) => {
    if (/^(?:bab|bagian|section|lampiran|daftar|profil|program|biaya|akreditasi|syarat|ketentuan)\b/i.test(line) || (/^[A-Z0-9 .:/-]{6,80}$/.test(line) && !/[.!?]$/.test(line))) {
      headings.push({ line: index + 1, text: line.slice(0, 140) });
    }
    if (/\t/.test(line) || /\s{2,}/.test(line) || /[|;]/.test(line) && /(?:rp|biaya|prodi|gelombang|tanggal|sks|akreditasi)/i.test(line)) {
      tables.push({ line: index + 1, text: line.slice(0, 180) });
    }
    if (/^(?:[-*•]|\d+[.)])\s+/.test(line)) lists.push({ line: index + 1, text: line.slice(0, 160) });
    if (/\?$|^(?:apa|bagaimana|berapa|kapan|dimana|apakah|kenapa)\b/i.test(line)) questionLike += 1;
  });
  return {
    lineCount: rawLines.length,
    headingCount: headings.length,
    tableLikeRowCount: tables.length,
    listItemCount: lists.length,
    questionLikeCount: questionLike,
    headings: headings.slice(0, 20),
    tableSamples: tables.slice(0, 12),
    listSamples: lists.slice(0, 12),
    structureType: tables.length >= 4 ? 'table_heavy' : questionLike >= 3 ? 'faq_like' : headings.length >= 3 ? 'structured_document' : 'plain_text'
  };
}

function detectFileType(filename = '') {
  const ext = path.extname(String(filename || '')).toLowerCase().replace(/^\./, '') || 'unknown';
  const parser = {
    pdf: 'pdf-parser-with-optional-ocr',
    docx: 'docx-parser',
    xlsx: 'excel-parser',
    xls: 'excel-parser',
    csv: 'csv-parser',
    txt: 'text-parser',
    jpg: 'image-ocr-parser',
    jpeg: 'image-ocr-parser',
    png: 'image-ocr-parser',
    webp: 'image-ocr-parser'
  }[ext] || 'generic-parser';
  return { extension: ext, parser };
}

function detectSourceAuthority(filename, sourceUrl, content = '') {
  const hay = normalize([filename, sourceUrl, content.slice(0, 2000)].filter(Boolean).join(' '));
  const registry = ensureSourceRegistry();
  let level = 'medium';
  const reasons = [];
  for (const rule of Array.isArray(registry.authorities) ? registry.authorities : []) {
    try {
      if (new RegExp(rule.pattern, 'i').test(hay)) {
        reasons.push(rule.reason || 'source_registry_match');
        if (rule.level === 'high') level = 'high';
        if (rule.level === 'low') level = 'low';
      }
    } catch (_) {}
  }
  if (/\b(?:sk|surat keputusan|lam infokom|ban pt|nomor sk|sertifikat)\b/.test(hay)) {
    level = 'high';
    reasons.push('official_document_signal');
  }
  if (/\b(?:draft|contoh|template|sample|dummy|sementara|belum final)\b/.test(hay)) {
    level = 'low';
    reasons.push('draft_or_template_signal');
  }
  return { level, reasons: reasons.length ? unique(reasons, 12) : ['filename_source_heuristic'], registryVersion: registry.version || 1 };
}
function extractDates(text) {
  const raw = String(text || '');
  const dates = [];
  for (const m of raw.matchAll(/\b\d{1,2}\s+(?:januari|februari|maret|april|mei|juni|juli|agustus|september|oktober|november|desember)\s+\d{4}\b/gi)) dates.push(m[0]);
  for (const m of raw.matchAll(/\b\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}\b/g)) dates.push(m[0]);
  for (const m of raw.matchAll(/\b(?:20\d{2})\s*[/\-]\s*(?:20\d{2})\b/g)) dates.push(m[0]);
  return unique(dates, 20);
}

function extractEffectiveDates(text) {
  const raw = compact(text);
  const snippets = [];
  const patterns = [
    /(?:berlaku|masa berlaku|valid sampai|valid hingga|periode|tahun ajaran|tahun akademik)[^.\n]{0,140}/gi,
    /(?:gelombang|pendaftaran)[^.\n]{0,140}(?:20\d{2}|januari|februari|maret|april|mei|juni|juli|agustus|september|oktober|november|desember)/gi
  ];
  for (const re of patterns) {
    for (const m of raw.matchAll(re)) snippets.push(m[0]);
  }
  return unique(snippets, 10);
}

function extractVersionSignals(text, filename) {
  const hay = compact([filename, text].filter(Boolean).join(' '));
  const versions = [];
  for (const m of hay.matchAll(/\b(?:versi|version|revisi|rev)\s*[:.-]?\s*([A-Za-z0-9.\-_/]+)\b/gi)) versions.push(m[0]);
  for (const m of hay.matchAll(/\b(?:tahun ajaran|tahun akademik|TA|T\.A)\s*[:.-]?\s*(20\d{2}\s*[/\-]\s*20\d{2})\b/gi)) versions.push(m[0]);
  return unique(versions, 10);
}

function extractEntities(text) {
  const hay = String(text || '');
  const entities = { programs: [], degrees: [], partners: [], services: [], accreditation: [], money: [], dates: extractDates(hay) };
  const programMap = [
    ['S2 Sistem Informasi', /\b(?:s2\s+sistem\s+informasi|magister\s+sistem\s+informasi|pascasarjana)\b/i],
    ['Sistem Informasi', /\bsistem\s+informasi\b/i],
    ['Teknologi Informasi', /\bteknologi\s+informasi\b/i],
    ['Bisnis Digital', /\bbisnis\s+digital\b/i],
    ['Sistem Komputer', /\bsistem\s+komputer\b/i],
    ['Manajemen Informatika', /\bmanajemen\s+informatika\b/i]
  ];
  for (const [label, re] of programMap) if (re.test(hay)) entities.programs.push(label);
  for (const [label, re] of [['S1', /\bS1\b|(?<!pasca\s?)\bsarjana\b/i], ['S2', /\bS2\b|magister|pascasarjana/i], ['D3', /\bD3\b|diploma/i]]) if (re.test(hay)) entities.degrees.push(label);
  for (const [label, re] of [['UTB', /\bUTB\b|universitas teknologi bandung/i], ['DNUI', /\bDNUI\b|dalian neusoft/i], ['HELP University', /\bHELP\b|help university/i]]) if (re.test(hay)) entities.partners.push(label);
  for (const [label, re] of [['INBIS', /\bINBIS\b|inkubator bisnis/i], ['Career Center', /career center|\bCDC\b|pusat kar/i], ['LLC', /\bLLC\b|language learning center/i], ['Student Exchange', /student exchange|pertukaran mahasiswa/i], ['GCCP', /\bGCCP\b|global cross cultural/i], ['BCCP', /\bBCCP\b/i], ['UKM/Ormawa', /\bUKM\b|ormawa|organisasi mahasiswa/i]]) if (re.test(hay)) entities.services.push(label);
  for (const m of hay.matchAll(/\b(?:unggul|baik\s+sekali|baik)\b/gi)) entities.accreditation.push(m[0]);
  for (const m of hay.matchAll(/(?:Rp\.?\s*\d[\d.\s]*(?:,-)?|\d[\d.\s]*(?:juta|jt|ribu|rb|rupiah))/gi)) entities.money.push(m[0]);
  for (const key of Object.keys(entities)) entities[key] = unique(entities[key], key === 'money' ? 25 : 12);
  return entities;
}

function extractAliases(entities) {
  const aliases = [];
  const add = (alias, canonical, type) => aliases.push({ alias: normalize(alias), canonical, type });
  for (const program of entities.programs || []) {
    if (program === 'Sistem Informasi') add('si', program, 'program');
    if (program === 'Teknologi Informasi') add('ti', program, 'program');
    if (program === 'Bisnis Digital') add('bd', program, 'program');
    if (program === 'Sistem Komputer') add('sk', program, 'program');
    if (program === 'Manajemen Informatika') add('mi', program, 'program');
    if (program === 'S2 Sistem Informasi') {
      for (const alias of ['s2', 'pasca', 'pascasarjana', 'pasca sarjana', 'magister', 'master']) add(alias, program, 'degree_program');
    }
  }
  for (const service of entities.services || []) {
    if (service === 'INBIS') add('inbis', 'Inkubator Bisnis', 'service');
    if (service === 'Career Center') add('cdc', 'Career Center', 'service');
    if (service === 'LLC') add('llc', 'Language Learning Center', 'service');
  }
  return aliases.filter((item, idx, arr) => arr.findIndex((x) => x.alias === item.alias && x.canonical === item.canonical) === idx).slice(0, 30);
}

function extractFacts(text) {
  const lines = String(text || '').split(/\r?\n/).map(compact).filter(Boolean);
  const facts = [];
  const factRe = /\b(?:akreditasi|biaya|pendaftaran|dpp|ukt|beasiswa|gelombang|program studi|alamat|kampus|student exchange|inkubator|career center|language learning|izin belajar|visa)\b/i;
  for (const line of lines) {
    if (line.length < 20 || line.length > 260) continue;
    if (factRe.test(line)) facts.push(line);
    if (facts.length >= 25) break;
  }
  return unique(facts, 25);
}

function extractRules(text) {
  const lines = String(text || '').split(/\r?\n/).map(compact).filter(Boolean);
  return unique(lines.filter((line) => /\b(?:harus|wajib|ketentuan|syarat|apabila|jika|tidak boleh|dikenakan|berlaku)\b/i.test(line)).slice(0, 20), 20);
}

function extractFaqCandidates(text) {
  const source = String(text || '');
  const out = [];
  const pairRegex = /(?:^|\n|\s)(?:\(?[QF]\)?|Question|Pertanyaan|Tanya)\s*[:.-]\s*([\s\S]*?)(?:\s+(?:\(?A\)?|Answer|Jawaban|Jawab)\s*[:.-]\s*)([\s\S]*?)(?=(?:\n|\s)(?:\(?[QF]\)?|Question|Pertanyaan|Tanya)\s*[:.-]|$)/gi;
  let match;
  while ((match = pairRegex.exec(source)) !== null) {
    const question = compact(match[1]);
    const answer = compact(match[2]);
    if (question.length >= 8 && answer.length >= 12) out.push({ question: question.slice(0, 220), answer: answer.slice(0, 500) });
    if (out.length >= 20) break;
  }
  return out;
}

function scoreQuality({ text, chunks, entities, facts, rules, faqCandidates, category, structure, authority }) {
  let score = 35;
  const reasons = [];
  if (text.length >= 500) score += 10; else reasons.push('short_text');
  if (chunks.length >= 2) score += 8; else reasons.push('few_chunks');
  if (category && category !== 'UNKNOWN') score += 10; else reasons.push('unknown_category');
  if ((entities.programs || []).length || (entities.services || []).length || (entities.partners || []).length) score += 10; else reasons.push('few_entities');
  if (facts.length >= 3) score += 10; else reasons.push('few_fact_candidates');
  if (rules.length || faqCandidates.length) score += 7;
  if ((entities.dates || []).length) score += 5;
  if ((entities.money || []).length) score += 5;
  if (structure && structure.structureType !== 'plain_text') score += 5;
  if (authority && authority.level === 'high') score += 7;
  if (authority && authority.level === 'low') { score -= 12; reasons.push('low_authority_source'); }
  if (structure && structure.lineCount > 30 && structure.headingCount === 0 && structure.tableLikeRowCount === 0) reasons.push('weak_document_structure');
  if (/ocr tidak menemukan|tidak ada teks terbaca|hasil scan/i.test(text)) { score -= 20; reasons.push('ocr_low_text_signal'); }
  if (/draft|template|contoh/i.test(text)) { score -= 8; reasons.push('draft_template_signal'); }
  score = Math.max(0, Math.min(100, score));
  return { score, band: score >= 78 ? 'high' : score >= 55 ? 'medium' : 'low', reasons };
}

function detectDuplicateSignals(text) {
  const normalized = normalize(text);
  return { contentHash: sha256(normalized), nearDuplicateKey: sha256(normalized.slice(0, 1200)), exactLength: normalized.length };
}

function detectConflictSignals({ entities, category, facts }) {
  const signals = [];
  if ((entities.money || []).length >= 8 && /BIAYA/.test(category || '')) signals.push('many_fee_values_check_wave_program_alignment');
  if ((entities.accreditation || []).length >= 2 && /AKREDITASI/.test(category || '')) signals.push('multiple_accreditation_grades_check_program_scope');
  if ((entities.dates || []).length >= 5) signals.push('many_dates_check_effective_period');
  if ((facts || []).some((line) => /menyusul|belum|tentatif|sementara/i.test(line))) signals.push('tentative_or_incomplete_fact');
  return signals;
}

function prepareKnowledgeDocument({ content, filename, sourceUrl, trainingDataId, divisionKey, storageType } = {}) {
  const rawText = String(content || '');
  const cleanedText = stripHeaderFooterNoise(rawText);
  const text = compact(cleanedText || rawText);
  const fileType = detectFileType(filename);
  const structure = detectDocumentStructure(cleanedText || rawText);
  const structuredTables = extractStructuredTables(cleanedText || rawText);
  const categoryDetailed = classifyDocumentCategoryDetailed(text, filename || '', { sourceUrl, divisionKey, storageType });
  const category = categoryDetailed && (categoryDetailed.category || categoryDetailed.bestCategory) || 'UNKNOWN';
  const chunks = chunkText(text, { minSize: 300, maxSize: 800 });
  const entities = extractEntities(text);
  const aliases = extractAliases(entities);
  const facts = extractFacts(cleanedText || text);
  const rules = extractRules(cleanedText || text);
  const faqCandidates = extractFaqCandidates(cleanedText || text);
  const authority = detectSourceAuthority(filename, sourceUrl, text);
  const versions = extractVersionSignals(text, filename);
  const effectiveDates = extractEffectiveDates(text);
  const duplicateSignals = detectDuplicateSignals(text);
  const conflictSignals = detectConflictSignals({ entities, category, facts });
  const quality = scoreQuality({ text, chunks, entities, facts, rules, faqCandidates, category, structure: { ...structure, structuredTableCount: structuredTables.length }, authority });
  const approvalReasons = unique([...quality.reasons, ...conflictSignals], 24);
  const mustReview = quality.band === 'low' || authority.level === 'low' || conflictSignals.length > 0 || category === 'UNKNOWN';
  const approval = {
    status: mustReview ? 'review_required' : 'auto_approved_candidate',
    reasons: approvalReasons,
    requiresHumanApproval: mustReview,
    decisionSource: 'knowledge_preparation_pipeline'
  };

  return {
    version: 3,
    generatedAt: new Date().toISOString(),
    trainingDataId: trainingDataId || null,
    filename: filename || null,
    sourceUrl: sourceUrl || null,
    divisionKey: divisionKey || null,
    storageType: storageType || null,
    documentIntake: {
      fileType,
      sourceAuthority: authority,
      preprocessing: {
        rawLength: rawText.length,
        cleanedLength: text.length,
        headerFooterRemovalApplied: rawText.length !== text.length
      }
    },
    documentUnderstanding: {
      category,
      categoryConfidence: categoryDetailed && categoryDetailed.confidence != null ? categoryDetailed.confidence : null,
      structure: { ...structure, structuredTableCount: structuredTables.length, structuredTableDomains: unique(structuredTables.map((table) => table.domain), 12) },
      structuredTables,
      versions,
      effectiveDates,
      entities,
      aliases
    },
    knowledgeExtraction: { factCandidates: facts, ruleCandidates: rules, faqCandidates },
    qualityControl: { duplicateSignals, conflictSignals, quality, approval },
    indexingPlan: {
      chunkCount: chunks.length,
      chunkMinMax: { minSize: 300, maxSize: 800 },
      embeddingRequired: true,
      indexVersioningRequired: true,
      indexEligibility: approval.status === 'auto_approved_candidate' ? 'eligible' : 'hold_for_review'
    }
  };
}
function buildKnowledgePreparationGovernance(record, baseMetadata = {}) {
  const metadata = baseMetadata && typeof baseMetadata === 'object' ? baseMetadata : {};
  const prep = record && typeof record === 'object' ? record : {};
  const understanding = prep.documentUnderstanding || {};
  const extraction = prep.knowledgeExtraction || {};
  const qualityControl = prep.qualityControl || {};
  const intake = prep.documentIntake || {};
  const duplicateSignals = qualityControl.duplicateSignals || {};

  return {
    ...metadata,
    knowledgePreparation: {
      version: prep.version || 3,
      generatedAt: prep.generatedAt || new Date().toISOString(),
      category: understanding.category || 'UNKNOWN',
      categoryConfidence: understanding.categoryConfidence != null ? understanding.categoryConfidence : null,
      sourceAuthority: intake.sourceAuthority || null,
      quality: qualityControl.quality || null,
      approval: qualityControl.approval || null,
      aliasCount: Array.isArray(understanding.aliases) ? understanding.aliases.length : 0,
      factCandidateCount: Array.isArray(extraction.factCandidates) ? extraction.factCandidates.length : 0,
      ruleCandidateCount: Array.isArray(extraction.ruleCandidates) ? extraction.ruleCandidates.length : 0,
      faqCandidateCount: Array.isArray(extraction.faqCandidates) ? extraction.faqCandidates.length : 0,
      structuredTableCount: Array.isArray(understanding.structuredTables) ? understanding.structuredTables.length : 0,
      structuredTableDomains: understanding.structure && Array.isArray(understanding.structure.structuredTableDomains)
        ? understanding.structure.structuredTableDomains
        : [],
      conflictSignals: Array.isArray(qualityControl.conflictSignals) ? qualityControl.conflictSignals : [],
      duplicateSignals,
      indexingPlan: prep.indexingPlan || null,
      indexVersion: {
        contentHash: duplicateSignals.contentHash || null,
        nearDuplicateKey: duplicateSignals.nearDuplicateKey || null,
        pipelineVersion: prep.version || 3,
        generatedAt: prep.generatedAt || new Date().toISOString()
      }
    }
  };
}

function appendKnowledgePreparationManifest(record) {
  fs.mkdirSync(path.dirname(MANIFEST_PATH), { recursive: true });
  fs.appendFileSync(MANIFEST_PATH, JSON.stringify(record) + '\n', 'utf8');
}

module.exports = {
  MANIFEST_PATH,
  SOURCE_REGISTRY_PATH,
  prepareKnowledgeDocument,
  buildKnowledgePreparationGovernance,
  appendKnowledgePreparationManifest,
  ensureSourceRegistry
};
